/**
 * The identity part of onboarding: team + default project + admin + service account.
 * Runs inside onboarding's TRANSACTION (takes `TkTx`, not `TkDb`).
 */
import { and, eq, sql } from "drizzle-orm";
import { ConflictError } from "@testkite/contract";
import { assertTenantContext, type TenantContext, type TkTx } from "../kernel/index.js";
import { apiTokens, memberships, projects, teams, users } from "./db/schema.js";
import { issueApiToken } from "./auth/issue.js";

export type TeamCore = {
  readonly teamId: string;
  readonly projectId: string;
  readonly adminUserId: string;
  /** true = the team was actually created this time; false = an idempotent replay on an existing team. */
  readonly created: boolean;
  readonly serviceTokenPrefix: string;
  /**
   * The secret leaves the process EXACTLY ONCE — only on the real creation call. An
   * idempotent replay returns `null`: the DB only ever keeps the sha256, there is no way
   * to read the old secret back.
   */
  readonly serviceToken: { readonly id: string; readonly prefix: string; readonly secret: string } | null;
};

export type ProvisionTeamInput = {
  readonly orgId: string;
  readonly name: string;
  readonly slug: string;
  readonly adminEmail: string;
  readonly serviceTokenDays: number;
};

/** Service account scope: can run tests and read results, CANNOT change anything. */
const SERVICE_SCOPES = ["run:trigger", "run:read", "case:read"] as const;

/**
 * `teamId` is generated by the CALLER beforehand and already sits in `app.team_id` — RLS on
 * `teams` is `WITH CHECK (id = app.team_id)`, so there is no other way to do this (spike
 * 2026-08-28).
 *
 * Idempotency here is arbitrated BY THE DB, not by read-then-write:
 *  - `ON CONFLICT DO NOTHING` (NOT just the arbiter) swallows both an `id` collision
 *    (replaying with the same idempotencyKey) and an `(org_id, slug)` collision (someone
 *    else already took the slug);
 *  - the two cases are told apart with exactly one SELECT under RLS: seeing a team with our
 *    own `id` ⇒ idempotent replay; not seeing it ⇒ the slug belongs to ANOTHER team ⇒ 409.
 * Never a cross-tenant SELECT, and no race window between the two statements.
 */
export async function provisionTeamCore(
  tx: TkTx,
  ctx: TenantContext,
  input: ProvisionTeamInput,
  now: Date,
): Promise<TeamCore> {
  const teamId = assertTenantContext(ctx);
  const inserted = await tx
    .insert(teams)
    .values({ id: teamId, orgId: input.orgId, name: input.name, slug: input.slug })
    .onConflictDoNothing()
    .returning({ id: teams.id });
  const created = inserted[0] !== undefined;
  if (!created) {
    const mine = await tx.select({ id: teams.id }).from(teams).where(eq(teams.id, teamId)).limit(1);
    if (mine[0] === undefined) throw new ConflictError(`slug already in use in this org: ${input.slug}`);
  }

  const proj = await tx
    .insert(projects)
    .values({ teamId, name: "Default", slug: "default" })
    .onConflictDoNothing({ target: [projects.teamId, projects.slug] })
    .returning({ id: projects.id });
  const projectId =
    proj[0]?.id ??
    (await tx.select({ id: projects.id }).from(projects).where(eq(projects.teamId, teamId)).limit(1))[0]?.id;
  if (projectId === undefined) throw new Error("onboarding: failed to create the project");

  /**
   * `users` is a GLOBAL table. Onboarding is only allowed to CREATE the first admin
   * account, NOT to sweep an existing account into a new team just because the caller
   * typed a matching email: doing that would force someone into a team they never agreed
   * to, with no invite, no notice. With no invite-accept flow yet (M3), the only safe path
   * is to REFUSE.
   *
   * The ONE exception: that person is ALREADY a member of this exact team — meaning this
   * is an idempotent replay of the same onboarding call, not a new attach.
   *
   * A weighed tradeoff: the 409 here tells the caller that email has an account. That
   * enumeration channel is only open to org_admin/instance_operator (the `team:create`
   * permission), and in exchange we close off forcing membership on an outsider — a much
   * smaller price.
   */
  const email = input.adminEmail.toLowerCase();
  const existingUser = await tx
    .select({ id: users.id })
    .from(users)
    .where(sql`lower(${users.email}) = ${email}`)
    .limit(1);
  const existingUserId = existingUser[0]?.id;
  if (existingUserId !== undefined) {
    const alreadyMember = await tx
      .select({ id: memberships.id })
      .from(memberships)
      .where(and(eq(memberships.teamId, teamId), eq(memberships.userId, existingUserId)))
      .limit(1);
    if (alreadyMember[0] === undefined) {
      throw new ConflictError(
        `adminEmail already belongs to an existing account: ${input.adminEmail} — add them via the invite flow, not onboarding`,
      );
    }
  }
  const adminUserId =
    existingUserId ??
    (
      await tx
        .insert(users)
        .values({ email, displayName: email.split("@")[0] ?? email })
        .onConflictDoNothing()
        .returning({ id: users.id })
    )[0]?.id;
  if (adminUserId === undefined) throw new Error("onboarding: failed to create the admin user");

  await tx
    .insert(memberships)
    .values({ teamId, userId: adminUserId, role: "team_admin" })
    .onConflictDoNothing({ target: [memberships.teamId, memberships.userId] });

  // Token is ONLY issued on the real creation call: an idempotent replay must not hand out extra credentials.
  if (created) {
    const minted = await issueApiToken(
      tx,
      { teamId },
      {
        name: "service-account",
        scopes: SERVICE_SCOPES,
        expiresInDays: input.serviceTokenDays,
        kind: "service",
        userId: null,
        createdBy: null,
      },
      now,
    );
    return {
      teamId,
      projectId,
      adminUserId,
      created,
      serviceTokenPrefix: minted.prefix,
      serviceToken: { id: minted.id, prefix: minted.prefix, secret: minted.secret },
    };
  }

  const existingToken = await tx
    .select({ prefix: apiTokens.prefix })
    .from(apiTokens)
    .where(and(eq(apiTokens.teamId, teamId), eq(apiTokens.kind, "service")))
    .orderBy(apiTokens.createdAt)
    .limit(1);
  const prefix = existingToken[0]?.prefix;
  if (prefix === undefined) throw new Error("onboarding: team already exists but is missing its service account");
  return { teamId, projectId, adminUserId, created, serviceTokenPrefix: prefix, serviceToken: null };
}
