version: '3.9'

services:
  mysql:
    image: mysql:5.7 # Replace with mysql:8.0.32 for m1
    platform: linux/x86_64 # Replace with linux/arm64/v8 for m1
    container_name: mysql
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testsigma_opensource
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
    ports:
      - "3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: out=$$(mysqladmin ping -h localhost -P 3306 -u root --password=root 2>&1); echo $$out | grep 'mysqld is alive' || { echo $$out; exit 1; }
      interval: 1s
      retries: 120

  frontend:
    build:
      context: ../../ui
      dockerfile: Dockerfile
    container_name: angular-app
    volumes:
      - ../../ui/dist/testsigma-angular:/usr/share/nginx/html

  backend:
    build:
      context: ../../server
      dockerfile: Dockerfile
    container_name: spring-boot-app
    ports:
      - "8080:8080"

  nginx:
    image: nginx:alpine
    container_name: nginx-server
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../../ui/dist/testsigma-angular:/usr/share/nginx/html
    depends_on:
      - frontend
      - backend
