version: '3.9'

services:
  mysql:
    image: mysql:5.7 # Replace with mysql:8.0.32 for m1
    platform: linux/x86_64 # Replace with linux/arm64/v8 for m1
    container_name: mysql
    restart: always
    volumes:
      - ./runtime_data/db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testsigma_opensource
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
    ports:
      - "3306:3307"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: out=$$(mysqladmin ping -h localhost -P 3306 -u root --password=root 2>&1); echo $$out | grep 'mysqld is alive' || { echo $$out; exit 1; }
      interval: 1s
      retries: 120
    networks:
      - proxy_network

  frontend:
    build:
      context: ../../ui
      dockerfile: Dockerfile
    container_name: angular-app
    volumes:
      - ../../ui/dist/testsigma-angular:/app/dist/testsigma-angular
    command: ["npx", "ng", "build", "--source-map", "--configuration=docker"]
    networks:
      - proxy_network

  backend:
    build:
      context: ../../
      dockerfile: Dockerfile
    container_name: spring-boot-app
    environment:
      JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    ports:
      - "9090:9090"
      - "5005:5005"
    volumes:
      - ./runtime_data/ts_data:/opt/app/ts_data
      - ../../automator:/opt/app/automator
      - ../../server:/opt/app/server
      - ./runtime_data/ts_data/file_store:/root/.testsigma/server/file_store
    depends_on:
      mysql:
        condition: service_healthy
    mem_limit: 1g
    networks:
      - proxy_network
    
  nginx:
    image: nginx:alpine
    container_name: nginx-server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx
      - ../../ui/dist/testsigma-angular:/usr/share/nginx/html
    depends_on:
      - frontend
      - backend
    networks:
      - proxy_network

networks:
  proxy_network:
    driver: bridge